jobs:
  - script: |
      // Root folder
      folder('PAD') {
          description('Root folder for PAD projects')
      }

      def jobDefinitions = ['project-a', 'project-b']
      def environments = ['dev', 'sit', 'uat']

      jobDefinitions.each { projectName ->

          folder("PAD + '/' + projectName") {
              description("Folder for ${projectName}")
          }
          environments.each { env ->
              def jobName = ""PAD + '/' + projectName + '/' + projectName +'-' + env"
              def scriptPathValue = "projectName + '/' + env + '.Jenkinsfile"

              pipelineJob(jobName) {
                description('Pipeline for ' + projectName + ' [' + env + ']')
                keepDependencies(false)

                // 4. Pipeline definition pointing to per-env Jenkinsfile
                definition {
                  cpsScm {
                    scm {
                      git {
                        remote { url cfg.repoUrl; credentials('gitlab') }
                        branch 'main'
                      }
                    }
                    scriptPath(projectName + '/' + env + '.Jenkinsfile')
                    lightweight(true)
                  }
                }

                disabled(false)
              }
          }
      }

