jobs:
    - script: |
    
        // === 1. สร้างโฟลเดอร์หลัก ===
        ['PAD', 'PAD/DevOps'].each { folderName ->
            folder(folderName) {
                description("Folder: ${folderName}")
            }
        }

        // === 2. config constants ===
        def repoUrl = 'https://github.com/padstrike/example-pipeline.git'
        def projects = ['project-a', 'project-b']
        def environments = ['dev', 'sit', 'uat']

        // === 3. Generate jobs ===
        projects.each { projectName ->
            def projectFolder = "PAD/${projectName}"

            folder(projectFolder) {
                description("Project folder for ${projectName}")
            }

            environments.each { env ->
                def jobName = "${projectFolder}/${projectName}-${env}"
                def jenkinsfilePath = "${projectName}/${env}.Jenkinsfile"

                try {
                    pipelineJob(jobName) {
                        description("Pipeline for ${projectName} [${env}]")
                        keepDependencies(false)

                        definition {
                            cpsScm {
                                scm {
                                    git {
                                        remote {
                                            url(repoUrl)
                                            credentials('gitlab')
                                        }
                                        branch('main')
                                    }
                                }
                                scriptPath(jenkinsfilePath)
                                lightweight(true)
                            }
                        }

                        disabled(false)
                    }
                } catch (Exception e) {
                    // หลีกเลี่ยง string interpolation เพื่อลด error JCasC
                    println '❌ Failed to create job: ' + e.toString()
                }
            }
        }

