# jobs-test-fetch.yaml
jobs:
  - script: >
      pipelineJob('job-dsl-plugin') {
        definition {
          cpsScm {
            scm {
              git {
                remote {
                  url('https://github.com/padstrike/Jenkins-config.git')
                }
                branch('*/main')
              }
            }
            scriptPath 'jobs-dsl/POC_pipeline.groovy'
            lightweight false
          }
        }
      }
