jobs:
    - script: |
    
        // Root folders
        ['PAD', 'PAD/DevOps'].each { path ->
            folder(path) {
                description("Folder: ${path}")
            }
        }

        // Constant repo URL for all jobs
        def repoUrl = 'https://github.com/padstrike/example-pipeline.git'

        // List of projects only
        def projects = ['project-a', 'project-b']
        def environments = ['dev', 'sit', 'uat']

        // Generate folders and jobs
        projects.each { projectName ->
            def basePath = "PAD/${projectName}"

            folder(basePath) {
                description("Project folder for ${projectName}")
            }

            environments.each { env ->
                def jobName = "${basePath}/${projectName}-${env}"
                def scriptPath = "${projectName}/${env}.Jenkinsfile"

                try {
                    pipelineJob(jobName) {
                        description("Pipeline for ${projectName} [${env}]")

                        keepDependencies(false)

                        definition {
                            cpsScm {
                                scm {
                                    git {
                                        remote {
                                            url(repoUrl)
                                            credentials('gitlab')
                                        }
                                        branch('main')
                                    }
                                }
                                scriptPath(scriptPath)
                                lightweight(true)
                            }
                        }

                        disabled(false)
                    }
                } catch (Exception e) {
                    println "❌ Failed to create job '${jobName}': ${e.message}"
                }
            }
        }
