# jobs.yaml
jobs:
  - script: >
      pipelineJob('Seed-All-Env-Pipelines') {
        definition {
          cpsScm {
            scm {
              git {
                // ใช้ remote(name, url, credentialsId)
                remote('origin',
                       'https://github.com/padstrike/Jenkins-config.git',
                       '')
                branches('*/main')
              }
            }
            scriptPath('jobs-dsl/POC_pipeline.groovy')
          }
        }
      }
