jobs:
    - script: |
        // 1. Define projects explicitly
        def jobDefinitions = [
          'project-a': [repoUrl: 'https://github.com/padstrike/example-pipeline.git'],
          'project-b': [repoUrl: 'https://github.com/padstrike/example-pipeline.git']
        ]

        // 2. Define environments
        def environments = ['dev', 'sit', 'uat']

        // 3. Loop through projects and environments
        jobDefinitions.each { projectName, cfg ->
          environments.each { env ->
            def jobName = 'PAD/' + projectName + '-' + env
            pipelineJob(jobName) {
              description('Pipeline for ' + projectName + ' [' + env + ']')
              keepDependencies(false)

              // 4. Pipeline definition pointing to per-env Jenkinsfile
              definition {
                cpsScm {
                  scm {
                    git {
                      remote { url cfg.repoUrl; credentials('gitlab') }
                      branch 'main'
                    }
                  }
                  scriptPath(projectName + '/' + env + '.Jenkinsfile')
                  lightweight(true)
                }
              }

              disabled(false)
            }
          }
        }