jobs:
  - script: |
      // Root folder
      folder('PAD') {
          description('Root folder for PAD projects')
      }

      def jobDefinitions = [
        'project-a',
        'project-b'
      ]

      def environments = ['dev', 'sit', 'uat']

      jobDefinitions.each { projectName ->

        // Create folder for each project under PAD
        folder("PAD/${projectName}") {
          description("Folder for ${projectName}")
        }

        environments.each { env ->
          def jobName = "PAD/${projectName}/${projectName}-${env}"

          pipelineJob(jobName) {
            description("Pipeline for ${projectName} [${env}]")
            keepDependencies(false)

            definition {
              cpsScm {
                scm {
                  git {
                    remote {
                      url('https://github.com/padstrike/example-pipeline.git')
                      credentials('gitlab')
                    }
                    branch('main')
                  }
                }
                scriptPath("${projectName}/${env}.Jenkinsfile")
                lightweight(true)
              }
            }

            disabled(false)
          }
        }
      }
