jobs:
  - script: |
      // Root folders
      folder('PAD') {
          description('Root folder for PAD projects')
      }

      def jobDefinitions = [
        'project-a': [repoUrl: 'https://github.com/padstrike/example-pipeline.git'],
        'project-b': [repoUrl: 'https://github.com/padstrike/example-pipeline.git']
      ]

      def environments = ['dev', 'sit', 'uat']

      jobDefinitions.each { projectName, cfg ->

        // Create folder for each project under PAD
        folder("PAD/${projectName}") {
          description("Folder for ${projectName}")
        }

        environments.each { env ->
          def jobName = "PAD/${projectName}/${projectName}-${env}"

          pipelineJob(jobName) {
            description("Pipeline for ${projectName} [${env}]")
            keepDependencies(false)

            definition {
              cpsScm {
                scm {
                  git {
                    remote {
                      url(cfg.repoUrl)
                      credentials('gitlab')
                    }
                    branch('main')
                  }
                }
                scriptPath("${projectName}/${env}.Jenkinsfile")
                lightweight(true)
              }
            }

            disabled(false)
          }
        }
      }
