
jobs:
  - script: |
      def environments = ['dev', 'sit', 'uat']
      def projects = findFiles(glob: 'project-*').findAll { it.directory }

      projects.each { proj ->
        def projectName = proj.name

        environments.each { env ->
          def jobName = "PAD/DevOps/${projectName}-${env}"

          pipelineJob(jobName) {
            description("Pipeline for ${projectName} [${env}]")
            keepDependencies(false)
            definition {
              cpsScm {
                scm {
                  git {
                    remote {
                      url 'https://github.com/padstrike/example-pipeline.git'
                      credentials('gitlab')
                    }
                    branch 'main'
                  }
                }
                scriptPath proj.path + "/${env}.Jenkinsfile"
                lightweight true
              }
            }

            disabled false
          }
        }
      }
